version: '3'

services:
  search_server:
    image: search_server:latest
    restart: on-failure
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    ports:
      - 8080:8080

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.0

    environment:
      - cluster.name=escontainers
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
